# .github/release.yml

changelog:
#  exclude:
#    labels:
#      - ignore-for-release
#    authors:
#      - octocat
  categories:
    - title: Breaking Changes 🛠
#      labels:
#        - Semver-Major
#        - breaking-change
    - title: Changes 🔃
#      labels:
#        - Semver-Minor
#        - enhancement
    - title: Bugfixes 🎉
#      labels:
#        - "*"
